INSERT INTO room (block, room_number, week_day, time, capacity, status) VALUES
                                                                            ('Northern', 'N1', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N1', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N1', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('Northern', 'N2', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N2', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N2', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('Northern', 'N3', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N3', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N3', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('Northern', 'N4', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N4', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N4', 'Friday', '4PM - 6PM', 70, 'Occupied'),


                                                                            ('Northern', 'N5', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N5', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N5', 'Friday', '4PM - 6PM', 70, 'Occupied'),


                                                                            ('Northern', 'N6', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N6', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N6', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('Northern', 'N7', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N7', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N7', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('Northern', 'N8', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N8', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N8', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('Northern', 'N9', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N9', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N9', 'Friday', '4PM - 6PM', 70, 'Occupied'),


                                                                            ('Northern', 'N10', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N10', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N10', 'Friday', '4PM - 6PM', 70, 'Occupied'),



                                                                            ('Northern', 'N11', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N11', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N11', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('Northern', 'N12', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'N12', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'N12', 'Friday', '4PM - 6PM', 70, 'Available'),


                                                                            ('TBH', 'TBH1', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH1', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH1', 'Friday', '4PM - 6PM', 70, 'Occupied'),


                                                                            ('TBH', 'TBH2', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH2', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH2', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('TBH', 'TBH3', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH3', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH3', 'Friday', '4PM - 6PM', 70, 'Occupied'),

                                                                            ('TBH', 'TBH4', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH4', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH4', 'Friday', '4PM - 6PM', 70, 'Occupied'),


                                                                            ('TBH', 'TBH5', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH5', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH5', 'Friday', '4PM - 6PM', 70, 'Available'),

                                                                            ('TBH', 'TBH6', 'Monday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH6', 'Friday', '4PM - 6PM', 70, 'Available'),

                                                                            ('TBH', 'TBH7', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH7', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH7', 'Friday', '4PM - 6PM', 70, 'Available'),

                                                                            ('TBH', 'TBH8', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH8', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH8', 'Friday', '4PM - 6PM', 70, 'Available'),

                                                                            ('TBH', 'TBH9', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'TBH9', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'TBH9', 'Friday', '4PM - 6PM', 70, 'Available'),



                                                                            ('TBH', 'LT1', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('TBH', 'LT1', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('TBH', 'LT1', 'Friday', '4PM - 6PM', 70, 'Available'),

                                                                            ('Northern', 'LT2', 'Monday', '7AM - 10AM', 70, 'Occupied'),
                                                                            ('Northern', 'LT2', 'Monday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Monday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Monday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Tuesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Tuesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Tuesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Tuesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Wednesday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Wednesday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Wednesday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Wednesday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Thursday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Thursday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Thursday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Thursday', '4PM - 6PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Friday', '7AM - 10AM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Friday', '10AM - 1PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Friday', '1PM - 4PM', 70, 'Available'),
                                                                            ('Northern', 'LT2', 'Friday', '4PM - 6PM', 70, 'Available');





-- Inserting sample data into the Timetable table
INSERT INTO timetable (week_day, unit_code, unit_name, lecture, venue, time, program, school, department, academic_year) VALUES
                                                                                                                             ('Monday', 'CS101', 'Introduction to Computer Science', 'Dr. Smith', 'TBH1', '10am - 1pm', 'Information Technology', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Tuesday', 'IT101', 'Introduction to Information Technology', 'Dr. Johnson', 'N1', '1pm - 4pm', 'Information Technology', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Wednesday', 'CS201', 'Data Structures', 'Prof. Lee', 'TBH3', '7am - 10am', 'Information Technology', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Wednesday', 'CS201', 'Data Structures', 'Prof. Lee', 'TBH3', '1pm - 4pm', 'Information Technology', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Thursday', 'IT201', 'Network Security', 'Prof. Davis', 'N2', '4pm - 7pm', 'Information Technology', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Friday', 'CS301', 'Algorithm Design', 'Dr. Brown', 'TBH4', '10am - 1pm', 'Information Technology', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Friday', 'CS301', 'Algorithm Design', 'Dr. Brown', 'TBH4', '7am - 10am', 'Information Technology', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Monday', 'CS101', 'Introduction to Computer Science', 'Dr. Smith', 'TBH1', '7am - 10am', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Monday', 'CS101', 'Introduction to Computer Science', 'Dr. Smith', 'TBH1', '1pm - 1pm', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Tuesday', 'IT101', 'Introduction to Information Technology', 'Dr. Johnson', 'N1', '10am - 1pm', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Tuesday', 'IT101', 'Introduction to Information Technology', 'Dr. Johnson', 'N1', '4pm - 7pm', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Wednesday', 'CS201', 'Data Structures', 'Prof. Lee', 'TBH3', '1pm - 4pm', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Wednesday', 'CS201', 'Data Structures', 'Prof. Lee', 'TBH3', '4pm - 7pm', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Thursday', 'IT201', 'Network Security', 'Prof. Davis', 'N2', '1pm - 4pm', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Thursday', 'IT201', 'Network Security', 'Prof. Davis', 'N2', '4pm - 7pm', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                             ('Friday', 'CS301', 'Algorithm Design', 'Dr. Brown', 'TBH4', '7am - 10am', 'Computer Science', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Monday', 'CS101', 'Introduction to Computer Science', 'Dr. Smith', 'TBH1', '7am - 10am', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Monday', 'CS101', 'Introduction to Computer Science', 'Dr. Smith', 'TBH1', '1pm - 1pm', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Tuesday', 'IT101', 'Introduction to Information Technology', 'Dr. Johnson', 'N1', '10am - 1pm', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Tuesday', 'IT101', 'Introduction to Information Technology', 'Dr. Johnson', 'N1', '4pm - 7pm', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Wednesday', 'CS201', 'Data Structures', 'Prof. Lee', 'TBH3', '1pm - 4pm', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Wednesday', 'CS201', 'Data Structures', 'Prof. Lee', 'TBH3', '4pm - 7pm', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Thursday', 'IT201', 'Network Security', 'Prof. Davis', 'N2', '1pm - 4pm', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Thursday', 'IT201', 'Network Security', 'Prof. Davis', 'N2', '4pm - 7pm', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One'),
                                                                                                                                ('Friday', 'CS301', 'Algorithm Design', 'Dr. Brown', 'TBH4', '7am - 10am', 'Software Engineering', 'Science and Computing', 'Information Technology', 'One');